---
metadata:
  name: "Ensure all modules are using the official AWS ones"
  id: "CKV2_GOOGLE_2"
  category: "SUPPLY_CHAIN"
definition:
  cond_type: attribute
  resource_types:
    - module
  attribute: source
  operator: starting_with
  value: terraform-google-modules

---
metadata:
 name: "Org's compute instances should not be e2-medium"
 id: "CKV2_GOOGLE_1"
 category: "NETWORKING"
definition:
   cond_type: "attribute"
   resource_types:
    - "google_compute_instance_template"
   attribute: "machine_type"
   operator: "not_equals"
   value: "e2-small"
